package vistas;

import medicamentos.Pedido;

public class FrmIntro extends javax.swing.JFrame {

    public FrmIntro() {
        initComponents();
        
        ocultarMsgError();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDistribuidor = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMedicamento = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        lblTipoMedicamento = new javax.swing.JLabel();
        cmbTipoMedicamento = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        lblDistribuidor = new javax.swing.JLabel();
        rdbCofarma = new javax.swing.JRadioButton();
        rdbEmpsephar = new javax.swing.JRadioButton();
        rdbCemefar = new javax.swing.JRadioButton();
        lblDespachar = new javax.swing.JLabel();
        chkPrincipal = new javax.swing.JCheckBox();
        chkSucursal = new javax.swing.JCheckBox();
        btnBorrar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblErrMedicamento = new javax.swing.JLabel();
        lblErrTipoMedicamento = new javax.swing.JLabel();
        lblErrCantidad = new javax.swing.JLabel();
        lblErrDistribuidor = new javax.swing.JLabel();
        lblErrSucursal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para pedido de medicamentos");
        setBackground(new java.awt.Color(204, 204, 255));
        setName("frmIntro"); // NOI18N

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Crear pedido");

        lblMedicamento.setLabelFor(txtMedicamento);
        lblMedicamento.setText("Medicamento: ");

        lblTipoMedicamento.setLabelFor(cmbTipoMedicamento);
        lblTipoMedicamento.setText("Tipo de medicamento: ");

        cmbTipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibiótico" }));

        lblCantidad.setText("Cantidad: ");

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblDistribuidor.setLabelFor(rdbCofarma);
        lblDistribuidor.setText("Distribuidor: ");

        btgDistribuidor.add(rdbCofarma);
        rdbCofarma.setText("Cofarma");
        rdbCofarma.setActionCommand("Cofarma");

        btgDistribuidor.add(rdbEmpsephar);
        rdbEmpsephar.setText("Empsephar");
        rdbEmpsephar.setActionCommand("Empsephar");

        btgDistribuidor.add(rdbCemefar);
        rdbCemefar.setText("Cemefar");
        rdbCemefar.setActionCommand("Cemefar");

        lblDespachar.setLabelFor(chkPrincipal);
        lblDespachar.setText("Despachar a: ");

        chkPrincipal.setText("Principal");

        chkSucursal.setText("Sucursal");

        btnBorrar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnConfirmar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblErrMedicamento.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        lblErrMedicamento.setForeground(new java.awt.Color(255, 0, 0));
        lblErrMedicamento.setText("Digite un medicamento");

        lblErrTipoMedicamento.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        lblErrTipoMedicamento.setForeground(new java.awt.Color(255, 0, 0));
        lblErrTipoMedicamento.setText("Seleccione un tipo");

        lblErrCantidad.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        lblErrCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lblErrCantidad.setText("Digite un valor numerico");

        lblErrDistribuidor.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        lblErrDistribuidor.setForeground(new java.awt.Color(255, 0, 0));
        lblErrDistribuidor.setText("Seleccione un distribuidor");

        lblErrSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        lblErrSucursal.setForeground(new java.awt.Color(255, 0, 0));
        lblErrSucursal.setText("Seleccione una sucursal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoMedicamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDistribuidor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDespachar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrMedicamento)
                    .addComponent(cmbTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrTipoMedicamento)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrCantidad)
                    .addComponent(rdbCofarma)
                    .addComponent(rdbEmpsephar)
                    .addComponent(rdbCemefar)
                    .addComponent(lblErrDistribuidor)
                    .addComponent(chkPrincipal)
                    .addComponent(chkSucursal)
                    .addComponent(lblErrSucursal))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrMedicamento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoMedicamento)
                    .addComponent(cmbTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrTipoMedicamento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblErrCantidad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDistribuidor)
                    .addComponent(rdbCofarma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbEmpsephar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbCemefar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrDistribuidor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblDespachar))
                    .addComponent(chkPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrSucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar)
                    .addComponent(btnBorrar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        boolean confirma = verificar();        
        if (confirma) {
            Pedido p = new Pedido();
            p.setMedicamento(this.txtMedicamento.getText());
            p.setTipoMedicamento(this.cmbTipoMedicamento.getSelectedItem().toString());
            p.setCantidad(Integer.parseInt(this.spnCantidad.getValue().toString()));
            p.setDistribuidor(this.btgDistribuidor.getSelection().getActionCommand());
            if (this.chkPrincipal.isSelected()) {
                p.setDespachar(this.chkPrincipal.getText());
            }
            if (this.chkSucursal.isSelected()) {
                p.setDespachar(this.chkSucursal.getText());
            }
            
            FrmImprime imp = new FrmImprime(p);
            imp.setVisible(true);
            imp.setLocationRelativeTo(this);
            limpiar();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed
    
    // Función que se encarga de ocultar los mensajes de error al iniciar la App.
    private void ocultarMsgError() {
        this.lblErrMedicamento.setVisible(false);
        this.lblErrTipoMedicamento.setVisible(false);
        this.lblErrCantidad.setVisible(false);
        this.lblErrDistribuidor.setVisible(false);
        this.lblErrSucursal.setVisible(false);
    }
    
    // Función que se encarga de restablecer los valores iniciales.
    private void limpiar() {
        //Limpia los campos
        this.txtMedicamento.setText("");
        this.cmbTipoMedicamento.setSelectedIndex(0);
        this.spnCantidad.setValue(0);
        this.btgDistribuidor.clearSelection();
        this.chkPrincipal.setSelected(false);
        this.chkSucursal.setSelected(false);
        ocultarMsgError();
        
    }
    
    // Función que se encarga de validar la información recibida.
    private boolean verificar() {
        if (this.txtMedicamento.getText().trim().equals("")) {
            ocultarMsgError();
            this.lblErrMedicamento.setVisible(true);
            this.txtMedicamento.requestFocus();
            return false;
        }
        
        if (this.cmbTipoMedicamento.getSelectedIndex() == 0) {
            ocultarMsgError();
            this.lblErrTipoMedicamento.setVisible(true);
            this.cmbTipoMedicamento.requestFocus();
            return false;
        }
        
        int cantidad = (Integer)this.spnCantidad.getValue();
        if (cantidad <= 0) {
            ocultarMsgError();
            this.lblErrCantidad.setVisible(true);
            this.spnCantidad.requestFocus();
            return false;
        }
        
        if (this.btgDistribuidor.getSelection() == null) {
            ocultarMsgError();
            this.lblErrDistribuidor.setVisible(true);
            this.rdbCofarma.requestFocus();
            return false;
        }
        
        if (!this.chkPrincipal.isSelected() && !this.chkSucursal.isSelected()) {
            ocultarMsgError();
            this.lblErrSucursal.setVisible(true);
            this.chkPrincipal.requestFocus();
            return false;
        }
        
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDistribuidor;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chkPrincipal;
    private javax.swing.JCheckBox chkSucursal;
    private javax.swing.JComboBox<String> cmbTipoMedicamento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDespachar;
    private javax.swing.JLabel lblDistribuidor;
    private javax.swing.JLabel lblErrCantidad;
    private javax.swing.JLabel lblErrDistribuidor;
    private javax.swing.JLabel lblErrMedicamento;
    private javax.swing.JLabel lblErrSucursal;
    private javax.swing.JLabel lblErrTipoMedicamento;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblTipoMedicamento;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rdbCemefar;
    private javax.swing.JRadioButton rdbCofarma;
    private javax.swing.JRadioButton rdbEmpsephar;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTextField txtMedicamento;
    // End of variables declaration//GEN-END:variables
}
